export {default as AvatarEditCV} from '../components/CV/AvatarEditCV';
export {default as BackDropCV} from '../components/CV/BackDropCV';
export {default as CardCV} from '../components/CV/CardCV';
export {default as CardMyCV} from '../components/CV/CardMyCV';
export {default as ContainerEditCV} from '../components/CV/ContainerEditCV';
export {default as LayoutEdit} from '../components/CV/LayoutEdit';
export {default as LayoutInput} from '../components/CV/LayoutInput';
export {default as SelectionBtn} from '../components/CV/SelectionBtn';
export {default as InputEditCV} from '../components/CV/InputEditCV';
export {default as CardInfo} from '../components/CV/CardInfo';
export * from './CV/NeumorphismHeader';
export {default as NeumorphismBtn} from './CV/NeumorphismBtn';
export * from './CV/HeaderGeneralCV2';
